#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 4
#SBATCH --ntasks-per-node 28
#SBATCH --cpus-per-task=1
#SBATCH --time 00:15:00
#SBATCH --partition veryshort
#SBATCH --reservation=COSC026662
#SBATCH --account=COSC026662
#SBATCH --exclude=compute[100-105,127,216,300]
#SBATCH --exclusive
#SBATCH --output d2q9-bgk.out

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

# source env.sh
#######################################
### Run the executable with OpenMP ####
#######################################
# ./d2q9-bgk input_128x128.params obstacles_128x128.dat
# ./d2q9-bgk input_128x256.params obstacles_128x256.dat
# ./d2q9-bgk input_256x256.params obstacles_256x256.dat
# ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat


##################################
## Run the executable with MPI ###
##################################
#------- mpirun -------#
# mpirun -np 112 ./d2q9-bgk input_128x128.params obstacles_128x128.dat
# mpirun -np 112 ./d2q9-bgk input_256x256.params obstacles_256x256.dat
# mpirun -np 112 ./d2q9-bgk input_128x256.params obstacles_128x256.dat
mpirun -np 112 ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

# mpirun -print-rank-map -np 112 ./d2q9-bgk input_128x128.params obstacles_128x128.dat
# mpirun -np 4 -genv I_MPI_PIN=1 -l ./d2q9-bgk input_128x128.params obstacles_128x128.dat
# mpirun -np 4 -ppn 2 -bind-to -l ./d2q9-bgk input_128x128.params obstacles_128x128.dat

#------- srun -------#
# srun --mpi=pmi2 ./d2q9-bgk input_128x128.params obstacles_128x128.dat
# srun --mpi=pmi2 -n 4 -l ./d2q9-bgk input_128x128.params obstacles_128x128.dat
# srun --mpi=pmi2 --ntasks=4 -l ./d2q9-bgk input_128x128.params obstacles_128x128.dat


############################################
### Colllect the results on Intel Advisor###
############################################
# advixe-cl --collect=roofline --project-dir=./advi_results -- ./d2q9-bgk input_128x128.params obstacles_128x128.dat
# advixe-cl --collect=roofline --project-dir=./advi_results -- ./d2q9-bgk input_256x256.params obstacles_256x256.dat
# advixe-cl --collect=roofline --project-dir=./advi_results -- ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

# srun --mpi=pmi2 advixe-cl -collect survey -project-dir ./advi_results ./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat

#---- opens up advisor gui ----#
# advisor-gui advi_results
